- .gitignore
- composer.lock
When we release a new version of the plugin we run `make release version=x.x.x` from
[https://github.com/dividohq/integrations-woocommerce/blob/master/ops/release/wp-release.sh](https://github.com/dividohq/integrations-woocommerce/blob/master/ops/release/wp-release.sh)
The basic stages of this script are:
1. clone this repo into a subfolder in [https://github.com/dividohq/integrations-woocommerce](https://github.com/dividohq/integrations-woocommerce)
2. `composer install --no-dev`
3. upload changes to svn repo http://plugins.svn.wordpress.org/finance-gateway-for-woocommerce/
The new version of the plugin is now immediately available for upgrade
Prior to this fix when `composer install --no-dev` is run there are some new composer packages added which are not contained in the previous …
> fix: breaking release

- composer.json
When making a new release and uploading the code to svn there was a "pre-commit webhook error"
```
PHP error in: finance-gateway-for-woocommerce/trunk/vendor/symfony/polyfill-mbstring/bootstrap80.php:
Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in Standard input code on line 15
Errors parsing Standard input code
```
The svn obviously doesn't like the use of "|" character [here](https://github.com/symfony/polyfill-mbstring/blob/main/bootstrap80.php#L15) used for as a [bitwise OR](https://stackoverflow.com/questions/13811922/what-does-using-a-single-pipe-in-a-function-argument-do) in php 8 
SImilar to the issue related to this [fix ](https://github.com/dividohq/finance-plugin-woocommerce/pull/68) the conflicted versions for **symfony/polyfill-mbstring** was …
> Feat fix psr7 load

- class-wc-gateway-finance.php
- readme.txt
Jira ticket: https://divido.atlassian.net/browse/SCB-198
Nordea have request that their logo is larger. This method checks if the finance environment is nordea and makes it a height of 24px rather than the standard 18px high.
Found [this on Stackoverflow](https://stackoverflow.com/questions/40723517/add-an-icon-to-custom-woocommerce-payment-gateway) which seems to work.
> fix: add customisable logo

- class-wc-gateway-finance.php
The calculator widget will now fetch the correct js file depending on the environment. e.g.  sandbox js file http://cdn.divido.com/widget/v3/divido.sandbox.calculator.js?ver=1
> fix(calculator-widget): update urls for each environment

- .github/pull_request_template.md
Adds a PR template to ensure all developers are aware of the need for an EOT character within translation references
> chore: adds pr template

- class-wc-gateway-finance.php
`checkHealth()` gets URL from the SDK instance so doesn't need it as a parameter
Also, removing API key from the SDK instance used for healthcheck to avoid leaking API key
> fix: remove unnecessary parameter

- class-wc-gateway-finance.php
This PR fixes the issue where the incorrect environment was being returned from the cache after the environments switched in the settings. It does this by hashing the url and using that as a part of the key.
> fix: [LM2-351] fix caching environment

- class-wc-gateway-finance.php
- readme.txt
> fix: Adjusted the way we set values to the config fields.

- class-wc-gateway-finance.php
- readme.txt
PR to retrieve the lender logo from the lender, via the finance plans call to the merchant-api-pub, rather than doing it in an ad-hoc way within the plugin.
> feat: LM2-1284 branding lender logo

- class-wc-gateway-finance.php
- composer.json
- includes/exceptions/ResponseException.php
- includes/proxies/MerchantApiPubProxy.php
- includes/wrappers/HttpApiWrapper.php
- readme.txt
This PR looks to bump the Merchant API SDK to a version compatible with *reasons*, before work to wedge reasons into the Wordpress admin interface 
That's the headline. In reality, this PR looks to do away with the use of `divido/merchant-sdk-guzzle-6` a) so that we can send that repo into cold storage and b) so that we don't have a guzzle dependency for our plugin (which is causing issues with plugins also utilising versions of Guzzle).A smarter person may have created their own PSR7 Client. I've instead utilised the [Wordpress HTTP API](https://developer.wordpress.org/plugins/http-api/#get-the-body-you-always-wanted) to handle all http requests, and done away with HTTP Clients altogether. We're instead just using the SDK to construct the payload for the requests.
PR also fixes a small …
> feat: LM2-2166 merchant sdk bump

- includes/proxies/MerchantApiPubProxy.php
- includes/wrappers/HttpApiWrapper.php
TLDR; This PR bumps the HTTP API timeout from 5 seconds to 30 seconds
Auto-activations are currently returning the following error on staging:
> Error during status transition. Error in response: cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received
I don't envision this being an issue on Prod, as we should receive the response quicker, but probably best to err on the side of caution and bump it up to 30 seconds, plus, it's always handy for things to actually work in Staging, especially when it's not particularly detrimental to the customer experience
> chore: increase timeout

- readme.txt
Missed a version bump in the readme. Should align with the version [here](https://github.com/dividohq/finance-plugin-woocommerce/blob/8860ef1c67c4c618044c53ee1fc9a16e84c9f2a8/class-wc-gateway-finance.php#L18C7-L18C7)
> chore: bumps version

- class-wc-gateway-finance.php
- includes/proxies/MerchantApiPubProxy.php
- readme.txt
This PR looks to extend the functionality of our shortcode widget to pick up on the price of a product so that the calculator generated by the widget automatically uses the price of the product (if no default price is given). The shortcode is also beholden to the rules in the plugin config (ie. min product price threshold), so it will not display if it doesn't adhere to the config rules. This is because the primary use for this functionality is to act as a fallback option for any compatibility issues with themers (like Beaver Themer), as was the case [here](https://divido.atlassian.net/browse/SCB-2021), so that merchants can use the shortcode to show the widget if it doesn't display conventionally.
The PR also fixes the path for the refund request endpoint
> fix: SCB-2021 product shortcode extension

- class-wc-gateway-finance.php
Somehow managed to lose the footnote part of the calculator. This fix sends the necessary data attribute to the calculator code, if set in the config panel
> fix: adds missing footnote

- includes/wrappers/HttpApiWrapper.php
Just a quick rollback on using the `mixed` type, as we still evidently have users on PHP 7.4, so this PHP 8 implementation is causing issues.
> fix: remove use of mixed

- .gitignore
- composer.json
- phpunit.xml
- tests/bootstrap.php
- tests/unit/GatewayTest.php
Little PR to add a structure to apply rudimentary unit tests for the plugin, using the [make command](https://github.com/dividohq/integrations-woocommerce/commit/eadf777e647ba4be84eebc19817b7e36f93b000a) in the parent development docker environment repo. Needs a bit of refinement, but good for a first pass.
> chore: unit tests

- class-wc-gateway-finance.php
Includes the country for the billing address, and adds a shipping address to the application request. Shipping address reverts to the billing address if not given. Restructures the address format to align with how the information is used in the `applicaiton-api`. This is to obtain compatibility with Oney.
Also removes the requirement for a deposit from the calculator (and assume the deposit is 0), as the calculator seems to be a little reluctant to give us this information these days, if the deposit amount is 0.
> feat: LM2-2240 shipping address

- class-wc-gateway-finance.php
- readme.txt
Little bump and readme update for v2.7.2 of the plugin, as is the way with Woocommerce
> chore: bump to v2.7.2

- includes/proxies/MerchantApiPubProxy.php
Fixes a few oopsies in the previous PR. Ideally we need the API Key to inform the plugin which version to send in the header, but that's a task for another day, I guess.
> fix: divido version header

- .github/pull_request_template.md
- includes/class-wc-gateway-finance.php
- package.json
- readme.txt
- tests/bootstrap.php
- tests/unit/GatewayTest.php
- woocommerce-gateway-finance.php
Small change for Woocommerce to notify merchants when an order has been referred, changing the status of the order to `on-hold` when the store receives the `REFERRED` webhook from us, then transitioning it to `pending-payment` when the store receives an `ACCEPTED` webhook.
Also uses consts and switches, because I'm fancy like that.
Ed: Using this PR to bump the version and administer a bit of upkeep too.
> feat: extends status triggers
